// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO8H0l8EyDjIGpnVXGBNojrFIkHnJlEkE',
    appId: '1:1072502416293:web:99c11270928d9d3893be4c',
    messagingSenderId: '1072502416293',
    projectId: 'mealmate-ffdf7',
    authDomain: 'mealmate-ffdf7.firebaseapp.com',
    storageBucket: 'mealmate-ffdf7.firebasestorage.app',
    measurementId: 'G-GHR1CL3692',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogxXRHxpf6t4nPZm9Lb5LNp1EsPoYEuE',
    appId: '1:1072502416293:android:96ea3747ddd2c58c93be4c',
    messagingSenderId: '1072502416293',
    projectId: 'mealmate-ffdf7',
    storageBucket: 'mealmate-ffdf7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE2LSHX1QX9Pw364zUWd-T21KTrwE4dZ0',
    appId: '1:1072502416293:ios:b79de196fcda5d9093be4c',
    messagingSenderId: '1072502416293',
    projectId: 'mealmate-ffdf7',
    storageBucket: 'mealmate-ffdf7.firebasestorage.app',
    iosBundleId: 'com.example.mealmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE2LSHX1QX9Pw364zUWd-T21KTrwE4dZ0',
    appId: '1:1072502416293:ios:b79de196fcda5d9093be4c',
    messagingSenderId: '1072502416293',
    projectId: 'mealmate-ffdf7',
    storageBucket: 'mealmate-ffdf7.firebasestorage.app',
    iosBundleId: 'com.example.mealmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO8H0l8EyDjIGpnVXGBNojrFIkHnJlEkE',
    appId: '1:1072502416293:web:a200d6bc7e0b185793be4c',
    messagingSenderId: '1072502416293',
    projectId: 'mealmate-ffdf7',
    authDomain: 'mealmate-ffdf7.firebaseapp.com',
    storageBucket: 'mealmate-ffdf7.firebasestorage.app',
    measurementId: 'G-7043JRPH38',
  );
}
